apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: workshop-dotnet-blue_green_deployments_openshift
  title: Blue-Green Deployments
  description: |
    Blue-Green Deployments with .NET
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - bluegreen
    - dotnet
  links:
    - url: https://<server>/#<repo>
      title: "Launch from Dev Spaces"
      icon: web
spec:
  type: module
  lifecycle: production
  owner: group:default/workshop-admins
  subcomponentOf: component:default/workshop-repository
